5일차 ORM/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),

    # 데이터 삭제에 대한 URL 패턴
    path('<int:article_pk>/delete/', views.delete, name='delete'),

    # 데이터 수정값 받는 페이지에 대한 URL 패턴
    path('<int:article_pk>/edit/', views.edit, name='edit'),

    # 데이터 수정 로직에 대한 URL 패턴
    path('<int:article_pk>/update/', views.update, name='update'),
]

5일차 ORM/crud/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

5일차 ORM/articles/models.py
from django.db import models

# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

5일차 ORM/newspapers/models.py
from django.db import models

# Create your models here.


class Newspaper(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField()
    journalist = models.CharField(max_length=80)
    created_at = models.DateTimeField(auto_now_add=True)

5일차 ORM/todos/models.py
from django.db import models

# Create your models here.


class Todo(models.Model):
    content = models.CharField(max_length=80)
    completed = models.BooleanField(default=False)
    priority = models.IntegerField(default=3)
    created_at = models.DateField(auto_now_add=True)
    deadline = models.DateField(null=True)

5일차 ORM/articles/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.


def index(request):
    # DB에 전체 게시글 조회를 요청하고 쿼리셋을 응답받아 저장
    articles = Article.objects.all()
    # print(articles)
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)


def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article': article,
    }

    return render(request, 'articles/detail.html', context)


def new(request):
    return render(request, 'articles/new.html')


def create(request):
    # new에서 보낸 사용자 데이터를 받아야 함
    # print(request.GET)
    title_1 = request.POST.get('title')
    content_1 = request.POST.get('content')

    # 받은 데이터를 DB에 저장
    # 3번 방법은 되도록이면..사용X. 제약조건이 적용 안됨
    # Article.objects.create(title=title_1, content=content_1)

    article = Article(title=title_1, content=content_1)
    # 저장 전 유효성 검사
    article.save()

    # 결과 페이지 반환
    # return render(request, 'articles/create.html')

    # 결과 페이지(전체 조회 템플릿) 반환하면 안되나?
    # return render(request, 'articles/index.html')
    # 이렇게 하면 좀 이상한 페이지로 감 데이터 전체조회하지 않다 보니 데이터가 안나옴.

    # 여기부터는 페이지 대신 주소 응답 !!
    # 이동할 주소 (URL) 반환 (사용자에게 응답)
    # 페이지를 만드는 개념이 아니라 templates, context 만들 필요 없음.
    # return redirect('articles:index')
    #
    # 생성한 글의 단일 조회(detail) 주소(url)로 이동 응답
    return redirect("articles:detail", article.pk)


def delete(request, article_pk):
    # 삭제할 데이터 조회
    article = Article.objects.get(pk=article_pk)

    # 조회한 데이터 삭제 (DELETE)
    article.delete()

    # 전체 조회 페이지 이동
    return redirect("articles:index")


def edit(request, article_pk):
    # 수정할 데이터 조회
    article = Article.objects.get(pk=article_pk)

    context = {
        'article': article,
    }
    return render(request, 'articles/edit.html', context)


def update(request, article_pk):
    # 수정 작업 과정
    # 1. 데이터 조회
    article = Article.objects.get(pk=article_pk)

    # 2. 데이터 수정
    # 2-1. 사용자가 입력한 form 데이터 저장
    title = request.POST.get('title')
    content = request.POST.get('content')

    # 2-2. 조회한 데이터(article)의 필드 값 변경
    article.title = title
    article.content = content

    # 3. 데이터 저장
    article.save()

    return redirect('articles:detail', article.pk)

5일차 ORM/newspapers/views.py
from django.shortcuts import render

# Create your views here.

5일차 ORM/todos/views.py
from django.shortcuts import render

# Create your views here.

5일차 ORM/articles/templates/articles/create.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>create</h1>
    <p>작성이 완료되었습니다 !</p>
  </body>
</html>

5일차 ORM/articles/templates/articles/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>detail</h1>
    <p>제목: {{article.title}}</p>
    <p>내용: {{article.content}}</p>
    <p>작성일: {{article.created_at}}</p>
    <p>수정일: {{article.updated_at}}</p>
    <form action="{% url 'articles:delete' article.pk %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="삭제" />
    </form>
    {% comment %} form태그 대신 a태그 사용해도 되긴 하는데 a태그는 디폴트가 GET
    이라... 웬만하면 form 쓰기 input 대신 button 쓰고 type만 submit으로 바꿔주면
    됨 {% endcomment %}

    <a href="{% url 'articles:edit' article.pk %}">수정하기</a>
    <a href="{% url 'articles:index' %}">뒤로가기</a>
  </body>
</html>

5일차 ORM/articles/templates/articles/edit.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>Edit</h1>
    <form action="{% url 'articles:update' article.pk %}" method="POST">
      {% csrf_token %}
      <div>
        <label for="title">제목: </label>
        <input type="text" name="title" id="title" value="{{article.title}}" />
      </div>

      <div>
        <label for="content">내용: </label>
        <textarea name="content" id="content" cols="30" rows="30">
{{article.content}}</textarea
        >
      </div>

      <input type="submit" value="수정하기" />
    </form>
    <a href="{% url 'articles:index' %}">뒤로가기</a>
  </body>
</html>

5일차 ORM/articles/templates/articles/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>articles</h1>
    <a href="{% url 'articles:new' %}">[NEW]로 이동</a>
    {% for article in articles %}
    <p>
      제목 :
      <a href="{% url 'articles:detail' article.pk %}">{{article.title}}</a>
    </p>
    <hr />
    {% endfor %}
  </body>
</html>

5일차 ORM/articles/templates/articles/new.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>New</h1>
    <form action="{% url 'articles:create' %}" method="POST">
      {% csrf_token %}
      <div>
        <label for="title">제목: </label>
        <input type="text" name="title" id="title" />
      </div>

      <div>
        <label for="content">내용: </label>
        <textarea name="content" id="content" cols="30" rows="30"></textarea>
      </div>

      <input type="submit" />
    </form>
    <a href="{% url 'articles:index' %}">뒤로가기</a>
  </body>
</html>