6일차 ORM w. view/sixth/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls')),
]

6일차 ORM w. view/todos/urls.py
from django.urls import path
from . import views

app_name = 'todos'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('<int:todo_pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
]

6일차 ORM w. view/todos/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField(null=True)
    completed = models.BooleanField(default=False)
    priority = models.IntegerField(default=3)
    created_at = models.DateField(auto_now_add=True)
    deadline = models.DateField(null=True)

6일차 ORM w. view/todos/views.py
from django.shortcuts import render
from .models import Todo

# Create your views here.
def index(request):
    todos = Todo.objects.all()
    context = {
        'todos':todos,
    }
    
    return render(request, 'todos/index.html', context)


def detail(request, todo_pk):
    todo_1 = Todo.objects.get(pk=todo_pk)
    context = {
        'todo_pk': todo_1,
    }
    return render(request, 'todos/detail.html', context)


def new(request):
    return render(request, 'todos/new.html')


def create(request):
    title_1 = request.GET.get('title')
    content_1 = request.GET.get('content')
    completed_1 = request.GET.get('completed')
    priority_1 = request.GET.get('priority')
    deadline_1 = request.GET.get('deadline')
    
    a = Todo(title=title_1, content=content_1, completed=completed_1, priority=priority_1, deadline=deadline_1)
    a.save()
    
    return render(request, 'todos/create.html')

6일차 ORM w. view/templates/base.html
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Base</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
      crossorigin="anonymous"
    />
    <style>
      {% block style %}{% endblock style %}
    </style>
  </head>
  <body>
    {% block content %} {% endblock content %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

6일차 ORM w. view/todos/templates/todos/create.html
{% extends 'base.html' %} {% block content %}

<h2>작성이 완료되었습니다!</h2>

{% endblock content %}

6일차 ORM w. view/todos/templates/todos/detail.html
{% extends 'base.html' %} {% block content %}

<div class="card" style="width: 18rem">
  <div class="card-body">
    <p>Title: {{todo_pk.title}}</p>

    <div class="mb-2 text-body-secondary">
      <p>Content: {{todo_pk.created_at}}</p>
      <p>
        Completed: {% if todo_pk.completed == True %} Y {% else %} N {% endif %}
      </p>
      <p>Deadline: {{todo_pk.deadline}}</p>
    </div>
  </div>

  <a type="button" class="btn btn-warning" href="{% url 'todos:index' %}"
    >뒤로 가기</a
  >
</div>

{% endblock content %}

6일차 ORM w. view/todos/templates/todos/index.html
{% extends 'base.html' %} {% block content %}

<nav class="navbar text-align" style="z-index: 100">
  <div class="container-fluid">
    <h1 class="m-3">TO DO List</h1>
    <a
      type="button"
      class="btn btn-warning m-3 shadow rounded"
      href="{% url 'todos:new' %}"
      >할 일 추가</a
    >
  </div>
</nav>
<div class="container">
  <div class="row">
    {% for i in todos %}
    <div
      class="col-3 card border-light shadow m-5 bg-body-tertiary rounded"
      style="max-width: 20rem"
    >
      <div class="card-header">Title : {{i.title}}</div>

      <div class="card-body text-secondary">
        <p>Content : {{i.content}}</p>
        <hr />

        <p>
          Completed : {% if i.completed == True %} Y {% else %} N {% endif %}
        </p>
        <hr />

        <p>priority : {{i.priority}}</p>
        <hr />

        <p>deadline : {{i.deadline}}</p>
        <hr />
      </div>

      <div class="card-footer d-flex justify-content-end">
        <a
          class="btn btn-dark"
          href="{% url 'todos:detail' i.pk %}"
          role="button"
          >자세히</a
        >
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock content %}

6일차 ORM w. view/todos/templates/todos/new.html
{% extends 'base.html' %} {% block content %}
<h1>할 일 추가</h1>

<div class="card m-2 p-4">
  <form action="{% url 'todos:create' %}" method="GET">
    <div>
      <label for="title">Title</label>
      <input type="text" name="title" id="title" />
    </div>

    <div>
      <label for="content">Content</label>
      <input type="text" name="content" id="content" cols="30" rows="30" />
    </div>

    <div>
      <label for="Completed">Completed?</label>
      <input type="text" name="completed" id="completed" />
    </div>

    <div>
      <label for="priority">Priority</label>
      <input type="text" name="priority" id="priority" />
    </div>

    <div>
      <label for="deadline">Deadline</label>
      <input type="text" name="deadline" id="deadline" />
    </div>
    <input type="submit" />
  </form>
</div>
<a href="{% url 'todos:index' %}">뒤로 가기</a>

{% endblock content %}