7일차 ORM w. view - 2/seventh/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls')),
]

7일차 ORM w. view - 2/todos/urls.py
from django.urls import path
from . import views


app_name = 'todos_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:todo_pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:todo_pk>/delete/', views.delete, name='delete'),
    path('<int:todo_pk>/edit/', views.edit, name='edit'),
    path('<int:todo_pk>/update/', views.update, name='update'),
]

7일차 ORM w. view - 2/todos/models.py
from django.db import models

# Create your models here.

class Todo(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField(null=True)
    completed = models.BooleanField(default=False)
    priority = models.IntegerField(default=3)
    created_at = models.DateField(auto_now_add=True)
    deadline = models.DateField(null=True)

7일차 ORM w. view - 2/todos/views.py
from django.shortcuts import render, redirect
from .models import Todo

# Create your views here.
def index(request):
    todos =  Todo.objects.all()
    context = {
        'todos':todos,
    }
    return render(request, 'todos/index.html', context)


def detail(request, todo_pk):
    todo_pk = Todo.objects.get(pk=todo_pk)
    context = {
        'todo': todo_pk,
    }
    
    return render(request, 'todos/detail.html', context)


def new(request):
    return render(request, 'todos/new.html')


def create(request):
    title_1 = request.POST.get('title')
    content_1 = request.POST.get('content')
    completed_1 = request.POST.get('completed')
    priority_1 = request.POST.get('priority')
    deadline_1 = request.POST.get('deadline')
    
    todo = Todo(title=title_1, content=content_1, completed=completed_1, priority=priority_1, deadline=deadline_1)
    todo.save()
    
    return redirect('todos_app:detail', todo.pk)


def delete(request, todo_pk):
    todo = Todo.objects.get(pk=todo_pk)
    todo.delete()
    return redirect('todos_app:index')


def edit(request, todo_pk):
    todo = Todo.objects.get(pk=todo_pk)
    context = {
        'todo': todo,
    }
    
    return render(request, 'todos/edit.html', context)

def update(request, todo_pk):
    todo = Todo.objects.get(pk=todo_pk)
    todo.title = request.POST.get('title')
    todo.content = request.POST.get('content')
    todo.completed = request.POST.get('completed')
    todo.priority = request.POST.get('priority')
    todo.deadline = request.POST.get('deadline')

    todo.save()
    
    return redirect('todos_app:detail', todo.pk)

7일차 ORM w. view - 2/todos/templates/todos/detail.html
{% extends 'base.html' %} {% block content %} 

<h1>DETAIL</h1>

<div class="card" style="width: 25rem">
    <div class="card-body">
      <p>Title: {{todo.title}}</p>
  
      <div class="mb-2 text-body-secondary">
        <p>Content: {{todo.content}}</p>
        <p>Priority: {{todo.priority}}</p>
        <p>
          Completed: {% if todo.completed == True %} Y {% else %} N {% endif %}
        </p>
        <p>Deadline: {{todo.deadline}}</p>

        <form action="{% url 'todos_app:delete' todo.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="REMOVE" />
          </form>


      </div>
    </div>
  <div class="d-flex"> 
    <a type="button" class="btn btn-warning" href="{% url 'todos_app:edit' todo.pk %}"
    >EDIT</a
  >
  <a type="button" class="btn btn-danger" href="{% url 'todos_app:delete' todo.pk %}"
  >REMOVE</a
>

    <a type="button" class="btn btn-dark" href="{% url 'todos_app:index' %}"
      >BACK</a
    >

  </div> 
    
  </div>
{% endblock content %}

7일차 ORM w. view - 2/todos/templates/todos/edit.html
{% extends 'base.html' %} {% block content %} 

<h1>Edit</h1>
    <form action="{% url 'todos_app:update' todo.pk %}" method="POST">
      {% csrf_token %}
      <div>
        <label for="title">TITLE</label>
        <input type="text" name="title" id="title" value="{{todo.title}}" />
      </div>

      <div>
        <label for="content">CONTENT</label>
        <textarea name="content" id="content" cols="30" rows="30">
{{todo.content}}</textarea
        >
      </div>

      <div>
        <label for="completed">Completed?</label>
        <textarea name="completed" id="completed" >
{{todo.completed}}</textarea
        >
      </div>

      <div>
        <label for="priority">PRIORITY</label>
        <textarea name="priority" id="priority" >
{{todo.priority}}</textarea
        >
      </div>

      <div>
        <label for="deadline">DEADLINE</label>
        <textarea name="deadline" id="deadline" >
{{todo.deadline}}</textarea
        >
      </div>

      <input type="submit" value="SUBMIT" />
    </form>
    <a href="{% url 'todos_app:index' %}">BACK</a>

{% endblock content %}

7일차 ORM w. view - 2/todos/templates/todos/index.html
{% extends 'base.html' %} {% block content %}

<nav class="navbar text-align" style="z-index: 100">
    <div class="container-fluid">
      <h1 class="m-3">TO DO LIST</h1>
      <a
        type="button"
        class="btn btn-warning m-3 shadow rounded"
        href="{% url 'todos_app:new' %}"
        >ADD</a
      >
    </div>
  </nav>
         

{% for i in todos %}
<ul>
    <a href="{% url 'todos_app:detail' i.pk %}" class="btn btn-dark" role="button"> {{i.title}}  </a> 
    
</ul>

{% endfor %}


{% endblock content %}

7일차 ORM w. view - 2/todos/templates/todos/new.html
{% extends 'base.html' %} {% block content %} 

<div class="container card m-2 p-4" style="width: 25rem">
 <div class="card-body">
    <form action="{% url 'todos_app:create' %}" method="POST">
        {% csrf_token %}

        <div>
        <label for="title">TITLE</label>
        <input type="text" name="title" id="title">
    </div>

    <div>
        <label for="content">CONTENT</label>
        <input type="text" name="content" id="content" cols="30" rows="30">
    </div>

    <div>
        <label for="Completed">Completed?</label>
        <input type="text" name="completed" id="completed" >
      </div>
  
      <div>
        <label for="priority">Priority</label>
        <input type="number" name="priority" id="priority" />
      </div>
  
      <div>
        <label for="deadline">Deadline</label>
        <input type="text" name="deadline" id="deadline" value="{{todo.deadline|date:'Y-m-d'}}" required/>
      </div>
      <input type="submit" value="SUBMIT">

    </form>

 </div>

 <a type="button" class="btn btn-warning" href="{% url 'todos_app:index' %}"
 >BACK</a>
</div>

{% endblock content %}